### PR TITLE
Ecto 3 support

### PR DESCRIPTION
**Pull request by joeapearson**
Also contains the changes from #178 .

@scottmessinger here are my latest changes in support of Ecto3.  Please can you take a look and merge if you're happy?  I believe you could close #178 since I pulled in all your changes (and those of our past contributors).

### CODE REVIEW

**Comment by scottmessinger** [comment]
@joeapearson This looks good! Quick question about compatibility -- while the upsert will require mongodb 4.4, will anything break if you use this with Mongo 4? If not, I'm +1 on merging this after I take a closer look! A quick review looked good.

**Comment by joeapearson** [comment]
@scottmessinger I'm pretty sure older versions of Mongo will continue to work in non-upsert cases but honestly I haven't checked.  I say live dangerously and we'll fix the bugs later :).

**Comment by johnnyshields** [comment]
Let's merge this :)

**Comment by joeapearson** [comment]
@scottmessinger please can you OK / not OK this and we'll merge.  Need to keep this thing moving I suppose!.

**Comment by scottmessinger** [comment]
@joeapearson Sorry for being MIA over the past 1.5 months! My goal is to cut a beta release this week!

**Comment by scottmessinger** [comment]
@joeapearson @johnnyshields This PR is in `1.0.0-beta.2`! The initial work I had done is in `1.0.0-beta.1`, so we should be able to see if anything in this PR is breaking things more easily. 

Thanks everyone for the help! If everything goes well, we cut 1.0.0 by the end of 2022?

**Comment by johnnyshields** [comment]
I hope you mean by the end of 2021!

**Comment by scottmessinger** [comment]
@johnnyshields 🤦  yup! By the end of 2021!

**Comment by d-staehler** [comment]
Hey @scottmessinger, is there anything blocking a 1.0.0 release or is there anything I can do to help get it across the line? 

Lets make a 1.0.0 happen by the end of 2022 after all 😀

**Comment by scottmessinger** [comment]
@d-staehler Nothing I can think of! If this works, we can cut it this month! Btw, are you interested in getting involved? If so, I'm happy to provide any help I can as you navigate the code base!

**Pull request merged**
